// generated by stringer -type=TokenType -output=lex_string.go; DO NOT EDIT

package tis100mc

import "fmt"

const _TokenType_name = "TokenCommentTokenLabelTokenInstructionTokenArgumentTokenComma"

var _TokenType_index = [...]uint8{12, 22, 38, 51, 61}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	hi := _TokenType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _TokenType_index[i-1]
	}
	return _TokenType_name[lo:hi]
}
